/**
 * Email validation utilities
 * Blocks disposable/temporary email domains
 */

// List of disposable email domains to block
const DISPOSABLE_EMAIL_DOMAINS = [
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'coolyopmail.com',
  'jetable.fr',
  'jetable.org',
  'temp-mail.org',
  'tempmail.com',
  'temp-mail.com',
  'tempmailaddress.com',
  'throwawaymail.com',
  'throwaway.email',
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamail.biz',
  'guerrillamail.de',
  'guerrillamail.info',
  'sharklasers.com',
  'spam4.me',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator.info',
  'mailinator.club',
  'supermailinator.com',
  'fakeinbox.com',
  'fakeinbox.net',
  'fakeinbox.org',
  'getairmail.com',
  'getairmail.net',
  'getairmail.org',
  'airmail.cc',
  'mailnesia.com',
  'tempinbox.com',
  'tempinbox.net',
  'tempinbox.org',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.de',
  'trashmail.io',
  'mytrashmail.com',
  'mytrashmail.net',
  'mytrashmail.org',
  'mohmal.com',
  'mohmal.net',
  'mohmal.org',
  'tempail.com',
  'tempail.net',
  'tempail.org',
  'emailondeck.com',
  'emailondeck.net',
  'emailondeck.org',
  'burner.kiwi',
  'temp-mail.io',
  'tempmails.com',
  'tempmails.net',
  'tempmails.org',
  'disposablemail.com',
  'disposablemail.net',
  'disposablemail.org',
  'maildrop.cc',
  'maildrop.io',
  'dispostable.com',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'tempr.email',
  'instantemail.io',
  'tempmailbox.com',
  'tempmailbox.net',
  'tempmailbox.org',
  'tempmailer.com',
  'tempmailer.net',
  'tempmailer.org',
  'tempm.com',
  'tempm.net',
  'tempm.org',
  'throwawaymail.net',
  'throwawaymail.org',
  'throwawaymail.info',
  'onedaymail.com',
  'onedaymail.net',
  'onedaymail.org',
  'mailcatch.com',
  'mailcatch.net',
  'mailcatch.org',
  'bouncr.com',
  'bouncr.net',
  'bouncr.org',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'anonymbox.com',
  'anonymbox.net',
  'anonymbox.org',
  'hidemail.de',
  'hidemail.net',
  'hidemail.org',
  'hidemail.com',
  'mailforspam.com',
  'mailforspam.net',
  'mailforspam.org',
  'mailforspam.info',
  'mailforspam.io',
  'spambox.us',
  'spambox.info',
  'spambox.irish',
  'spambox.works',
  'mytemp.email',
  'mytempemail.com',
  'mytempemail.net',
  'mytempemail.org',
  'temporarymail.com',
  'temporarymail.net',
  'temporarymail.org',
  'gettempmail.com',
  'gettempmail.net',
  'gettempmail.org',
  'fakemail.net',
  'fakemail.io',
  'fakemail.co',
  'fakemail.com',
  'tempmailo.com',
  'tempmailo.net',
  'tempmailo.org',
  'tempmaili.com',
  'tempmaili.net',
  'tempmaili.org',
  'tempemails.io',
  'tempemails.net',
  'tempemails.org',
  'tempemails.com',
  'tempemail.co',
  'tempemail.net',
  'tempemail.org',
  'tempemail.io',
  'tempemail.info',
  'tempemail.com',
  'tempmail.plus',
  'tempmail.plus',
  'tempmail.in',
  'tempmail.es',
  'tempmail.de',
  'tempmail.fr',
  'tempmail.it',
  'tempmail.nl',
  'tempmail.pl',
  'tempmail.ru',
  'tempmail.cn',
  'tempmail.jp',
  'tempmail.kr',
  'tempmail.tw',
  'tempmail.hk',
  'tempmail.sg',
  'tempmail.au',
  'tempmail.nz',
  'tempmail.uk',
  'tempmail.ca',
  'tempmail.us',
  'tempmail.mx',
  'tempmail.br',
  'tempmail.ar',
  'tempmail.cl',
  'tempmail.co',
  'tempmail.io',
  'tempmail.app',
  'tempmail.dev',
  'tempmail.tech',
  'tempmail.site',
  'tempmail.xyz',
  'tempmail.club',
  'tempmail.space',
  'tempmail.world',
  'tempmail.pro',
  'tempmail.biz',
  'tempmail.info',
  'tempmail.name',
  'tempmail.me',
  'tempmail.cc',
  'tempmail.tv',
  'tempmail.ws',
  'tempmail.fm',
  'tempmail.am',
  'tempmail.at',
  'tempmail.be',
  'tempmail.ch',
  'tempmail.dk',
  'tempmail.fi',
  'tempmail.gr',
  'tempmail.ie',
  'tempmail.li',
  'tempmail.lt',
  'tempmail.lu',
  'tempmail.lv',
  'tempmail.mt',
  'tempmail.pt',
  'tempmail.se',
  'tempmail.si',
  'tempmail.sk',
];

/**
 * Validates email format using regex
 */
export function validateEmailFormat(email: string): boolean {
  // RFC 5322 simplified regex - more strict validation
  const emailRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;
  return emailRegex.test(email);
}

/**
 * Checks if email domain is in the disposable email blacklist
 */
export function isDisposableEmail(email: string): boolean {
  const domain = email.toLowerCase().split('@')[1];
  if (!domain) return true; // Invalid email, treat as disposable
  return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}

/**
 * Full email validation - checks format and domain
 * Returns an object with isValid and error message
 */
export function validateEmail(email: string): { isValid: boolean; error: string | null } {
  if (!email || email.trim() === '') {
    return { isValid: false, error: 'Veuillez entrer une adresse email' };
  }

  if (!validateEmailFormat(email)) {
    return { isValid: false, error: 'Veuillez entrer une adresse email valide' };
  }

  if (isDisposableEmail(email)) {
    return { isValid: false, error: 'Les adresses email jetables ne sont pas autorisées' };
  }

  return { isValid: true, error: null };
}
